### PR TITLE
[WIP] Testing the Simple Gateway

### PR DESCRIPTION
**Pull request by naveenkunareddy**
Testing the Simple Gateway

### CODE REVIEW

**Comment by naveenkunareddy** [comment]
please test this

**Comment by anshprat** [comment]
@naveenkunareddy am guessing this PR presently is only for making a build / dev setup where you can make further changes?

@sorenh Naveen is a member of network engineering, please approve.

**Comment by naveenkunareddy** [comment]
yes, making the build for testing SimpleGateway feature.

**Comment by naveenkunareddy** [comment]
please test this

**Comment by sorenh** [comment]
ok to test

**Comment by naveenkunareddy** [comment]
please test this

**Comment by naveenkunareddy** [comment]
please test this

**Comment by naveenkunareddy** [comment]
please test this

**Pull request closed without merging**
