### PR TITLE
Enable debug

### PR DESCRIPTION
**Pull request by hkumarmk**
Enabling debug would be required to enable troubleshooting easier.

TODO: need to set logrotation to make sure this will not cause disks to be full.

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
@bodepd any reason on closing this? In fact it is required to enable verbose/debug to troubleshoot operations in production. I had discussed this with @sorenh I would need to add a appropriate logrotate though.

**Comment by bodepd** [comment]
I didn't realize you were considering merging this into prod, I thought you were just debugging something

**Comment by hkumarmk** [comment]
im just merging this for now, we may need to add appropriate log rotation which have noted in the issue #528

**Pull request merged**
