### PR TITLE
A few hardening related changes

### PR DESCRIPTION
**Pull request by sorenh**

### CODE REVIEW

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by bodepd** [comment]
It passed. It did result in 313 errors in tempest ( I was thinking the desired result was closer to 300, so it might be effecting the cloud, but honestly until we get tempest tests gating, we can't really use it to stop code from coming in)

**Pull request merged**
