### PR TITLE
fixed dependency errors

### PR DESCRIPTION
**Pull request by hkumarmk**

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
what is the symptom of this?

**Comment by hkumarmk** [comment]
bodepd, i m still working on this patch, - this was because we had changed the argument for contrail_rt, but missed to change the name of deps, but it need more changes (we need to add hiera for rt number so that it support different rts)

**Comment by hkumarmk** [comment]
please test this

**Pull request merged**
