### PR TITLE
Nova flavor purge

### PR DESCRIPTION
**Pull request by hkumarmk**
* Create nova flavors
* Use flavor name for tempest
  * This need the patch jiocloud/puppet-tempest#9 to be merged
* Purge unmanaged nova flavors

This is a superset of PRs #401 and #396. The review and merge can be done on all individual PRs or only this PR.

Here are the dependant patches which need to be merged before this one.

* jiocloud/puppet-tempest#9
* JioCloud/puppet-nova#1
* JioCloud/puppet-nova#1
* JioCloud/puppet-openstack_extras#2
* JioCloud/puppet-openstacklib#1

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
last test failed because of timeout - otherwise the validation tests were successful (running tempest tests there)

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
previous test failed because of timeout, I see validation tests were sucess there.

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
again timeout :(... checking why this is happening

**Comment by hkumarmk** [comment]
I see ocdb took long time to complete puppet run, Ill try testing again.

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
there are three different patches here for flavors, can you clean it up and ensure that only the patch that I should review exists?

**Comment by bodepd** [comment]
dup of #396

**Comment by bodepd** [comment]
I reviewed everything and it looks fine.

**Comment by bodepd** [comment]
replaced by #456

**Pull request closed without merging**
