### PR TITLE
adding ssh-rsa keys for harshalgupta

### PR DESCRIPTION
**Pull request by harshalgupta**
adding harshalgupta rsa keys

### CODE REVIEW

**Comment by mayankkapoor** [comment]
Harshal is in the Reliance Jio Cloud storage team, reports to Abhishek.

**Comment by sorenh** [comment]
ok to test

**Comment by sorenh** [comment]
please test this

**Comment by harshalgupta** [comment]
please test this

**Comment by harshalgupta** [comment]
please test this

**Comment by mayankkapoor** [comment]
Merging pull request as both checks have passed, and the modifications are to the correct files.

**Pull request merged**
