### PR TITLE
osd test should handle loop devices also

### PR DESCRIPTION
**Pull request by hkumarmk**
This patch will make ceph test work for loop devices also where the partition
have different naming convention.

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by sorenh** [comment]
Just FYI, I have a patch planned for Overcast that will let us spin up st nodes with as many volumes attached as we want so that we don't have to muck around with loop devices.

**Comment by hkumarmk** [comment]
sure

**Pull request merged**
