### PR TITLE
Adding myself (Neeraj Agrawal)

### PR DESCRIPTION
**Pull request by neeraj8us**

### CODE REVIEW

**Comment by anshprat** [comment]
Hi Neeraj,
Please get approval/confirmation from one of your team mates/manager.

**Comment by ajayaa** [comment]
Only the owners of Jiocloud will be able to invite people into Jiocloud team. So either Mayank or Hari should add Neeraj to Jiocloud organization.

**Comment by mayankkapoor** [comment]
@neeraj8us I've invited you to the JioCloud organization.
@anshprat Do you suggest @neeraj8us close this pull request and open a new one with same modifications, or if the changes look good can we go ahead and merge?

**Comment by anshprat** [comment]
Looks good, merging.

**Pull request merged**
