### PR TITLE
 Add swami's public key

### PR DESCRIPTION
**Pull request by swamireddy**

### CODE REVIEW

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by anshprat** [comment]
Looking into the builds failure (they are not related to this PR)

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
tests passed, merging this.

**Comment by anshprat** [comment]
oops. @swamireddy I see some other changes as part of this PR :! Please open a separate one for them. Please keep only the key changes in this PR. Not merging this presently.

**Comment by bodepd** [comment]
I'm closing this since it conflates changes related to quotas with adding a key. Please resubmit as 2 separate pull requests.

**Comment by bodepd** [comment]
This build passed, it just took twice as long as expected and timed out at 1 1/2 hours. I verified that it started passing at 2 hours. I will explore the underlying build performance issues independently from this code review.

**Pull request closed without merging**
