### PR TITLE
UC|more overcast specific changes

### PR DESCRIPTION
**Pull request by hkumarmk**
* Disabling debug as the code within debug function will not work with overcast.
* Fix wrong flavor reference
* unset env_http[s]_proxy before running make_userdata.sh
* Added validation stuffs for undercloud to .overcast.yaml
* it seems overcast has a bug because of which the variable is not getting
extracted properly on remote execution commands, because of which verify_hosts,
trigger_update etc are failing using overcast. Added an issue for that, for now
using python jiocloud directly from deploy.sh.
* save cleanup files in ~/ so they can be used by delete job.
* get_ip_of_node once rather than in a loop - ip will be assigned before that
get exeecuted

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
looks good as soon as it passes.

**Pull request merged**
