### PR TITLE
adding my (sanjayu) keys

### PR DESCRIPTION
**Pull request by saneax**
please test it

### CODE REVIEW

**Comment by bodepd** [comment]
@saneax as an FYI, there is a known issue where 'please test this' doesn't run until the first travis tests have finished. Just note that you need to track to ensure that the tests are actually triggered, or wait until after travis finishes to initiate tests.

**Comment by saneax** [comment]
please test it

**Comment by saneax** [comment]
please test it

**Comment by saneax** [comment]
please test it

**Comment by bodepd** [comment]
please don't destroy this build. the failure is not related to your patch and I'm looking into it...

**Comment by bodepd** [comment]
darn, I think Harish's job overrode the jenkins job directory that I needed to do a recreate.

**Comment by bodepd** [comment]
I had a look at the job and since the failure has nothing to do with a successful build, I'm happy to merge

**Pull request merged**
