### PR TITLE
UC |DO NOT MERGE |To test neutron patch

### PR DESCRIPTION
**Pull request by hkumarmk**

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
this causes gcp1 to fail:

````
Jun 18 20:08:43 gcp1-testjenkins-puppet-rjil-gate-1541 ntpd[28178]: new interface(s) found: waking up resolver
Jun 18 20:08:53 gcp1-testjenkins-puppet-rjil-gate-1541 puppet-user[19218]: (/Stage[main]/Tempest/Tempest_config[network/public_network_id]) Could not evaluate: undefined method `id' for Neutron_network[public](provider=neutron):Puppet::Type::Neutron_network::ProviderNeutron
Jun 18 20:08:56 gcp1-testjenkins-puppet-rjil-gate-1541 puppet-user[19218]: Finished catalog run in 25.01 seconds
Jun 18 20:08:58 gcp1-testjenkins-puppet-rjil-gate-1541 logger: Puppet failed with return code 6, also failing validation
````

**Comment by hkumarmk** [comment]
oh :( ill see what can be done

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test overcloud

**Comment by hkumarmk** [comment]
please test overcloud

**Comment by hkumarmk** [comment]
please test overcloud

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by hkumarmk** [comment]
merged the puppet-neutron patch, so closing this

**Pull request closed without merging**
