### PR TITLE
Reduce the noise in deploy.sh output

### PR DESCRIPTION
**Pull request by hkumarmk**
There are lot of noise there in deploy.sh output because of ssh banners, so
reducing the noise by removing banner from ssh output.

Also just move trap statement and the function to the top from middle of the code.

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
this build looks like it passed, I can't figure out why it looks like it failed, it might be related to the code changes.

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
this patch does not work, it fails incorrectly when the build passes.

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
travis failure is because of openstack module issue which will be fixed after merging #640

**Comment by hkumarmk** [comment]
please test this

**Pull request merged**
