### PR TITLE
Kilo patch v1 block

### PR DESCRIPTION
**Pull request by anshprat**

### CODE REVIEW

**Comment by swamireddy** [comment]
This PR is pending to merge. Please review this PR asap.

**Comment by swamireddy** [comment]
@anshprat  Can you check this PR?

**Comment by anshprat** [comment]
@swamireddy cinder::quota::quota_backups
Where is the code to use this hiera? Can you point me to the relevant module in kilo branch using this variable?

**Comment by swamireddy** [comment]
Closing this PR.

**Pull request closed without merging**
