### PR TITLE
Kilo cinder backup limit

### PR DESCRIPTION
**Pull request by swamireddy**

### CODE REVIEW

**Comment by swamireddy** [comment]
@anshprat - Updated the PR. Can you plz check now?

**Comment by anshprat** [comment]
Looks good. Merging this now as its in kilo branch and will not impact existing stuff. Before merging kilo to master, we would need to get it gated and AT.

**Comment by anshprat** [comment]
oh wait, is this supposed to go into master? Or into kilo?

**Comment by swamireddy** [comment]
Closing this PR as its on master instead of kilo branch

**Pull request closed without merging**
