### PR TITLE
Set "global" tag for haproxy service on haproxy role

### LINKED ISSUE #372: ct1 exposes haproxy service in consul, but only acts as haproxy for Contrail
This is particularly problematic if haproxy.service.consul is used as a fake cname for creating dns entries in which case, it'll flap between haproxy1 and ct1.

### PR DESCRIPTION
**Pull request by sorenh**
Fixes #372

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
First test failed because of some issues on contrail ifmap server (Ill need to debug that error). Otherwise the change this PR meant for is happening.

**Comment by sorenh** [comment]
Second run failed due to puppet not getting installed. Destroying and trying again.

**Comment by sorenh** [comment]
Please test this

**Comment by hkumarmk** [comment]
last test failed because of puppet-common 3.7.4 deb not found in apt.puppetlabs.com. Retrying

**Comment by hkumarmk** [comment]
please test this

**Comment by sorenh** [comment]
Uh... I think one test run is sufficient :)

**Comment by hkumarmk** [comment]
It failed last two runs, but because of different reasons. The stuffs this patch does is happening there, so I can merge this as this patch is not affecting any existing functionalities.

**Comment by sorenh** [comment]
I understand, but I just kicked off a third test run 5 minutes ago. I don't think a lot changed in the 2-3 minutes between that one and the one you just started :)

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Pull request merged**
