### PR TITLE
Add my secret key

### PR DESCRIPTION
**Pull request by devendermishrajio**

### CODE REVIEW

**Comment by punituee** [comment]
please test this

**Comment by devendermishrajio** [comment]
retest this please

**Comment by devendermishrajio** [comment]
please test this

**Comment by devendermishrajio** [comment]
please test this

**Comment by devendermishrajio** [comment]
please test this

**Comment by punituee** [comment]
please test this

**Comment by devendermishrajio** [comment]
please test this

**Comment by devendermishrajio** [comment]
please test this

**Comment by anshprat** [comment]
err, this PR is incomplete, it will only add the key, not the account.
(i) see this for example - https://github.com/JioCloud/puppet-rjil/pull/620
(ii) This will also need a rebase now.

**Comment by devendermishrajio** [comment]
please test this

**Comment by anshprat** [comment]
Also, please squash the commits into a single msg.

**Comment by devendermishrajio** [comment]
please test this

**Comment by anshprat** [comment]
@mayankkapoor blocked on build, I verified this and looks good to go. Please merge.

**Pull request merged**
