### PR TITLE
Tempest run good tests

### PR DESCRIPTION
**Pull request by hkumarmk**
This need jiocloud/puppet-tempest#8 to be merged

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
Last test failed because gcp1 node did not get any IP address... seems we hit the issue on hp cloud.

**Comment by hkumarmk** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by bodepd** [comment]
@sorenh @hkumarmk @jaspreetw 39 failures :( Who should be looking into that?

**Comment by hkumarmk** [comment]
need to update test list

**Comment by sorenh** [comment]
QA team. They came up with the list.

**Comment by sorenh** [comment]
Oh, but that tempest patch hasn't landed yet. Is that why?

**Comment by hkumarmk** [comment]
yes it is, but theere is an updated list which need to be updated before get all tests passed

**Comment by bodepd** [comment]
Actually, this patch was targeting that branch, so it didn't need to be merged fist. I went ahead and merged it.

**Comment by hkumarmk** [comment]
@bodepd sure, ill update puppetfile

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
that test isn't going to pass without the test-exclusion updates, so why bother?

**Comment by hkumarmk** [comment]
I have updated it

**Comment by bodepd** [comment]
oh. sorry!

**Comment by sorenh** [comment]
So close! One failure. Rerunning to see if it was spurious.

**Comment by sorenh** [comment]
please test this

**Pull request merged**
