### PR TITLE
Add user and key for Swami

### PR DESCRIPTION
**Pull request by swamireddy**

### CODE REVIEW

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by bodepd** [comment]
there is something broken at the moment that we are working on fixing, builds will continue to fail until it is resolved.

**Comment by swamireddy** [comment]
ok

**Comment by Vaidyanath** [comment]
please test this

**Comment by swamireddy** [comment]
please test this

**Comment by bodepd** [comment]
this unfortunately will require a rebase now.

**Comment by bodepd** [comment]
I'm closing as this needs a rebase, open if it is still relevant.

**Pull request closed without merging**
