### PR TITLE
Vrouter debug

### PR DESCRIPTION
**Pull request by anshprat**
Puppetfile and fixtures changes are only for testing

### CODE REVIEW

**Comment by anshprat** [comment]
please test this

**Comment by hkumarmk** [comment]
why these extra commits?

you should rebase to master before you push the change

**Comment by anshprat** [comment]
please test this

**Comment by hkumarmk** [comment]
I see last build has the change this patch supposed to do, but it seems some issue with that build (consul has issues there - one says no leader, and failing. Also I see some weird errors in consul server, it seems it is trying to elect leader which are in different dc - wll need to debug more to understand it better. 

I am just triggering another build as ofn

**Comment by hkumarmk** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by bodepd** [comment]
@hkumarmk we really just need to kill all builds. One has gotten into this crazy state where it tries to get all nodes to join it's cluster.

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
related code change at https://github.com/JioCloud/jiocloud-contrail/pull/44

**Comment by anshprat** [comment]
https://github.com/JioCloud/jiocloud-contrail/pull/44

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by bodepd** [comment]
@anshprat thanks for splitting this up into two, I think we should do this from now on. One to ensure that the other change does not effect anything when it's not being set.

**Comment by bodepd** [comment]
please test this

**Pull request merged**
