### PR TITLE
WIP: (Don't merge) Test tempest updates

### PR DESCRIPTION
**Pull request by sorenh**

### CODE REVIEW

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by bodepd** [comment]
You know there is a parameterize build that does exactly this?

http://jiocloud.rustedhalo.com:8080/job/puppet_rjil_pkg_test/

**Comment by bodepd** [comment]
closing as this has been merged.

**Pull request closed without merging**
