### PR TITLE
UC | More changes for undercloud testing

### PR DESCRIPTION
**Pull request by hkumarmk**
* debug will not work in this form with overcast, also not sure about it support
in overcast, so disabling for overcast atm, will check on it later.
* jenkins is rewriting double quotes to single, which was causing issues, so
fixing it.

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
last one failed with the message "    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))"

hkumar [12:07 PM]
it should be from contrail - I see it happening before too

hkumar [12:08 PM]
testing again

**Comment by hkumarmk** [comment]
please test this

**Comment by anshprat** [comment]
tests passed, amar also reviewed. merging.

**Pull request merged**
