### PR TITLE
Adding soumit keys

### PR DESCRIPTION
**Pull request by hisoumit**
Add soumit keys

### CODE REVIEW

**Comment by Vaidyanath** [comment]
please test this

**Comment by Vaidyanath** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
ok to test

**Comment by hkumarmk** [comment]
please test this

**Comment by hisoumit** [comment]
please test this

**Comment by Vaidyanath** [comment]
please test this

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
ok to test

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
ok to test

**Comment by sorenh** [comment]
please test this

**Comment by sorenh** [comment]
Here we go :)

**Comment by Vaidyanath** [comment]
thank you

**Comment by Vaidyanath** [comment]
please test this

**Comment by swamireddy** [comment]
Please be sure that - update the repo, add your key on latest files and
submit.
PS: I couldn't see my keys, which were merged a long back.

**Comment by theanalyst** [comment]
@swamireddy your keys are still not merged btw see #374 , merge conflicts

**Comment by anshprat** [comment]
this is no longer required as soumit's key is already added via https://github.com/JioCloud/puppet-rjil/pull/550

**Pull request closed without merging**
