### PR TITLE
Add user and key for Alok Jani

### PR DESCRIPTION
**Pull request by alokjani**
Adds keys & user to Vagrant and AT envs

### CODE REVIEW

**Comment by alokjani** [comment]
please test this

**Comment by alokjani** [comment]
Unsure why this failed.

**Comment by alokjani** [comment]
please test this

**Comment by bodepd** [comment]
everything was kind of hosed: #333 (which I just merged should have resolved the issue).

to get started debugging, the easiest way to try to see what happened is to login to any node and run:

```
jorc get_failures --hosts
```

**Comment by bodepd** [comment]
please test this

**Pull request merged**
