### PR TITLE
Don't allow member to update internal virtual network and make it external

### PR DESCRIPTION
**Pull request by sajuptpm**
Closes-bug: https://bugs.launchpad.net/jio/+bug/1460051

Don't allow member to update internal virtual network and make it external

Issue:
"update_network:router:external": "rule:admin_only",
Above rule is missing in neutron/etc/policy.json of icehouse.
So member can update internal virtual network and make it external.

Fix:
Copy
https://github.com/openstack/neutron/blob/stable/icehouse/etc/policy.json
to "puppet-neutron/files" and add missing rule.

puppet-neutron PR:
https://github.com/JioCloud/puppet-neutron/pull/6

### CODE REVIEW

**Comment by bodepd** [comment]
I'd much prefer to have a commit message that describes the changes it contains as opposed to ones that reference a ticket number, I'm a huge fan of linking ticket number in the commit message, just not in the title.

**Comment by bodepd** [comment]
Also, this ticket claims to make one change, but it adds 50 additional rules, it might be the case that these are just the same as the default policies, but right now, the scope of the change here looks huge, and might take a time to go through.

**Comment by sajuptpm** [comment]
Actual changes are in puppet-neutron, there I mentioned ticket number and changes which I made.
https://github.com/JioCloud/puppet-neutron/pull/6/commits

That has two commits:

commit1 ---> Added  https://github.com/openstack/neutron/blob/stable/icehouse/etc/policy.json to puppet-neutron/files

commit2 ---> Added missing rule "update_network:router:external": "rule:admin_only",

**Comment by bodepd** [comment]
this patch doesn't do anything now. It just adds a file that isn't used.

**Comment by sajuptpm** [comment]
@bodepd PR updated

**Comment by sajuptpm** [comment]
please test this

**Comment by sajuptpm** [comment]
**Tested in build 1366 and works as expected.**

==========
###### Check Permission:

saju@ct1-testjenkins-puppet-rjil-gate-1366:~$ **sudo ls -l /etc/neutron/policy.json**
-rw-r--r-- 1 root root 5915 Jun  6 04:48 /etc/neutron/policy.json

==========
###### Check newly added rule:

saju@ct1-testjenkins-puppet-rjil-gate-1366:~$ **sudo cat /etc/neutron/policy.json  | grep "update_network:router:external"**
    "update_network:router:external": "rule:admin_only",

==========
###### Find a internal virtual network:

saju@ct1-testjenkins-puppet-rjil-gate-1366:~$ **neutron net-show 8b0c7b76-4643-4ac0-a78e-5203129ae1aa**
+-------------------------+---------------------------------------------------------------------------------------------------------------+
| Field                   | Value                                                                                                         |
+-------------------------+---------------------------------------------------------------------------------------------------------------+
| admin_state_up          | True                                                                                                          |
| contrail:fq_name        | default-domain                                                                                                |
|                         | testtenant                                                                                                    |
|                         | ct1-testjenkins-puppet-rjil-gate-1366-8b0c7b76-4643-4ac0-a78e-5203129ae1aa                                    |
| contrail:instance_count | 0                                                                                                             |
| contrail:subnet_ipam    | {"subnet_cidr": "10.0.0.0/24", "ipam_fq_name": ["default-domain", "default-project", "default-network-ipam"]} |
| id                      | 8b0c7b76-4643-4ac0-a78e-5203129ae1aa                                                                          |
| name                    | ct1-testjenkins-puppet-rjil-gate-1366                                                                         |
| **router:external         | False**                                                                                                         |
| shared                  | False                                                                                                         |
| status                  | ACTIVE                                                                                                        |
| subnets                 | 777eb317-596f-4776-9d32-b030caa3aabc                                                                          |
| tenant_id               | fa886271b2b74696b38937ff4d694f6a                                                                              |
+-------------------------+---------------------------------------------------------------------------------------------------------------+

==========
###### Try to update internal virtual network and set --router:external=True:

saju@ct1-testjenkins-puppet-rjil-gate-1366:~$ **neutron net-update 8b0c7b76-4643-4ac0-a78e-5203129ae1aa --router:external=True**
The resource could not be found.

**Comment by hkumarmk** [comment]
@sajuptpm why net-update gives "Resource could not be found" (404?)? instead of 403 or something?

**Comment by sajuptpm** [comment]
@hkumarmk , By default, neutron raises HTTPNotFound if Policy Not Authorized. I think, they done it intentionally to hide resource info from the user who has limited privileges.
https://github.com/openstack/neutron/blob/9d649129ca762f406846190d31997397f0a0c53b/neutron/api/v2/base.py#L195

**Comment by hkumarmk** [comment]
oh okay got that :) thanks. Once the system is up (there is one activity which cause a downtime for our floating ips), ill test it .

**Comment by sajuptpm** [comment]
@hkumarmk, 
Have you got a chance to test it ?

**Comment by hkumarmk** [comment]
lgtm

**Pull request merged**
