### PR TITLE
Limit number of backups to 240 per customer account

### PR DESCRIPTION
**Pull request by swamireddy**
Limit number of backups to 240 per customer account
Closes-bug# https://bugs.launchpad.net/jio/+bug/1472591

### CODE REVIEW

**Comment by swamireddy** [comment]
@anshprat : Can you please check these 2 patches?

**Comment by anshprat** [comment]
@swamireddy you need to open this PR against the kilo branch of puppet-rjil, not against master branch. Please close and open a new one against kilo branch.

**Comment by swamireddy** [comment]
@anshprat: This patch is based on kilo branch only.

**Comment by anshprat** [comment]
The destination needs to be kilo.  
swamireddy wants to merge 2 commits into JioCloud:master from swamireddy:kilo-patch-v1_block

**Comment by swamireddy** [comment]
Closing this PR as it has been raised based on master (it should be based on kilo branch)

**Pull request closed without merging**
