### PR TITLE
Adding the ssh keys.

### PR DESCRIPTION
**Pull request by bafna**
please test this

### CODE REVIEW

**Comment by bafna** [comment]
please test this

**Comment by bafna** [comment]
please test this

**Comment by bafna** [comment]
please test this

**Comment by bafna** [comment]
please test this

**Comment by anshprat** [comment]
please test this

**Comment by bafna** [comment]
please test this

**Comment by bafna** [comment]
please test this

**Comment by anshprat** [comment]
builds passed, merging.

**Pull request merged**
