### PR TITLE
increasing haproxy timeout, workaround for neutron bad statusline error

### PR DESCRIPTION
**Pull request by akash1808**

### CODE REVIEW

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
Either builds are failing temporarily or there may be a issue with the syntax as two builds have failed with Bad status line. Need to check once.

**Comment by hkumarmk** [comment]
@akash1808 this is what your patch is going to workround.... so it would need to reach production before this can be fixed

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by akash1808** [comment]
please test this

**Comment by hkumarmk** [comment]
I see it update the haproxy configuation. so merging

**Pull request merged**
