### PR TITLE
[Don't Merge] - Ceph RGW: Config Change for RGW Multipart Upload

### PR DESCRIPTION
**Pull request by abhidixit**
Change Min part size for Multipart Upload as per the requirement:
https://bugs.launchpad.net/jio/+bug/1457827

Default value for Min part size limit for Multipart Upload is 5 MB.
This is changed to 1 MB as per requirement.

### CODE REVIEW

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by swamireddy** [comment]
@abhidixit: Can we set this in puppet-rjil/manifests/{ceph.pp, ceph/radosgw.pp} files?

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by abhidixit** [comment]
please test this

**Comment by swamireddy** [comment]
@abhidixit: Can we set this in puppet-rjil/manifests/{ceph.pp, ceph/radosgw.pp} files? have you explored it?

**Comment by abhidixit** [comment]
@swamireddy : I think we can't do it in puppet-rjil. I have done this in puppet-ceph. This PR is to test my puppet-ceph repo changes.

**Comment by bodepd** [comment]
patch that this tests is merged, closing

**Pull request closed without merging**
