### PR TITLE
Squid proxy changes

### PR DESCRIPTION
**Pull request by hkumarmk**
Changed squid proxy setting according to squid-deb-proxy changes -
http://bazaar.launchpad.net/~mvo/+junk/squid-deb-proxy/view/head:/squid-deb-proxy.conf

### CODE REVIEW

**Comment by bodepd** [comment]
can we get this rebased? I'm going through some of the older patches and this looks like something that should get merged in.

**Comment by hkumarmk** [comment]
@bodepd done.. rebased

**Comment by anshprat** [comment]
This would help reducing the build time.. presently cache hit to cache miss is 1:2 !

**Comment by bodepd** [comment]
rebased as #689

**Pull request closed without merging**
