### PR TITLE
Adding my (sanjay) keys

### PR DESCRIPTION
**Pull request by saneax**
Add my ssh keys

### CODE REVIEW

**Comment by saneax** [comment]
please test this

**Comment by bodepd** [comment]
you might want to hold off on this until Rohit's keys are merged or rebase your patch off his branch. Otherwise, you'll still have to run gate tests after rebase.

**Comment by saneax** [comment]
OK, will rebase from Rohit's branch

On Wed, Jan 14, 2015 at 3:59 PM, Dan Bode <notifications@github.com> wrote:

> you might want to hold off on this until Rohit's keys are merged or rebase
> your patch off his branch. Otherwise, you'll still have to run gate tests
> after rebase.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/puppet-rjil/pull/308#issuecomment-69896848>.
>



-- 
Sanjay Upadhyay
http://saneax.blogspot.com

**Comment by saneax** [comment]
closing this pull request, will rebase after Rohit's keys are merged.

**Pull request closed without merging**
