### PR TITLE
UC | Setup apparmor

### PR DESCRIPTION
**Pull request by hkumarmk**
This patch to setup apparmor and manage apparmor rules.

This code would be using in various places where we need to change/add apparmor
rules.

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
@sorenh @bodepd please review this. This patch doesnt affect any functionality as of now.

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Pull request merged**
