### PR TITLE
Flavor name

### PR DESCRIPTION
**Pull request by hkumarmk**
Create nova flavors
Use flavor name for tempest
This need the patch JioCloud/puppet-tempest#9 to be merged
Purge unmanaged nova flavors
This is a superset of PRs #401 and #396. The review and merge can be done on all individual PRs or only this PR.

Here are the dependant patches which need to be merged before this one.

JioCloud/puppet-tempest#9
JioCloud/puppet-nova#1
JioCloud/puppet-nova#1
JioCloud/puppet-openstack_extras#2
JioCloud/puppet-openstacklib#1

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
last failure was an ntp failure on ceph, retrying build

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
@hkumarmk @sorenh  from a code/functionality perspective, this is ready to merge, but I think this one requires planning in terms of how it's rolled out to production (it breaks our layouts, I'm not sure if we can expect the existing flavors to be purged if they have images of that flavor type, etc...). I'm happy to say +1, but I think we should move this through CI separately from the rest of the reference architecture changes.

**Comment by sorenh** [comment]
Deleting flavors should be fine without affecting running instances.

Continuous deployment is hosed anyway, so this is hardly more disruptive than anything else anyway. If it works, ship it. There will be period of time of getting things rolling again anyway.

**Pull request merged**
