### PR TITLE
Support fip pool using contrail n neutron apis

### PR DESCRIPTION
**Pull request by hkumarmk**

### CODE REVIEW

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by amar266** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by amar266** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by amar266** [comment]
please test this

**Comment by amar266** [comment]
please test this

**Comment by mayankkapoor** [comment]
please test this

**Comment by hkumarmk** [comment]
please test this

**Comment by hkumarmk** [comment]
This worked on testharish-04101616, and whole build work except couple of things - floating ip test failed because of the wrong hiera which is fixed in last commit, gcp1 validation fail because of vgw failure. I am running another test build.

After the build work, I ssh to ocdb1/bootstrap node with tunnel the port 8143 to ct1 (ssh -L 8143:ct1-testharish-04101616:8143 49.40.64.173).

using my keystone admin credentials, I added admin to the tenants mgmt_tenant and internal_tenant

keystone user-role-add --user admin --tenant mgmt_tenant --role _member_
keystone user-role-add --user admin --tenant internal_tenant --role _member_

Now pointed my laptop's browser to https://localhost:8143, and logged in using admin credentials, clicked on configure tab (2nd) in left pane, clicked on "Networking" -> Manage floating ips. 

Now on right pane, I used appropriate tenant from 'project' dropdown, then clicked '+' and now added the details in the form, saved, repeated this for both ment_tenant and internal_tenant, thats it. Now I can see floating ips in neutron.

I allocated public floating ips (100.1.0.0/24)and private floating ips(99.0.0.0/24) to mgmt_tenant and only private floating ips to internal_tenant (99.0.0.0/24).

```
root@ocdb1-testharish-04101616:~# export OS_TENANT_NAME=mgmt_tenant
root@ocdb1-testharish-04101616:~# neutron floatingip-create public_net
Created a new floatingip:
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| fixed_ip_address    |                                      |
| floating_ip_address | 100.1.0.12                           |
| floating_network_id | a6cd0d5d-5cca-4470-8870-3c674d963c48 |
| id                  | e6c00c01-036c-49d6-9b61-7ec3277cb233 |
| port_id             |                                      |
| router_id           |                                      |
| status              | ACTIVE                               |
| tenant_id           | dd4d1d4fcf384fd7a85837d9a0e82a9c     |
+---------------------+--------------------------------------+
root@ocdb1-testharish-04101616:~# neutron floatingip-list
+--------------------------------------+------------------+---------------------+---------+
| id                                   | fixed_ip_address | floating_ip_address | port_id |
+--------------------------------------+------------------+---------------------+---------+
| 4464f49a-0699-4084-9341-c18f9128ef33 |                  | 99.0.0.3            |         |
| e6c00c01-036c-49d6-9b61-7ec3277cb233 |                  | 100.1.0.12          |         |
+--------------------------------------+------------------+---------------------+---------+
root@ocdb1-testharish-04101616:~# export OS_TENANT_NAME=internal_tenant
root@ocdb1-testharish-04101616:~# neutron floatingip-list
+--------------------------------------+------------------+---------------------+---------+
| id                                   | fixed_ip_address | floating_ip_address | port_id |
+--------------------------------------+------------------+---------------------+---------+
| e4aebe27-7281-4656-ac92-ea3059016c95 |                  | 99.0.0.2            |         |
+--------------------------------------+------------------+---------------------+---------+
```

**Comment by hkumarmk** [comment]
last test failed because of a github problem (puppet-librarian failed)

**Comment by hkumarmk** [comment]
building new one - harish-04110421

**Comment by hkumarmk** [comment]
sorry this one harish-04110424

**Comment by bodepd** [comment]
it failed b/c it does not pass lint tests.

```
manifests/keystone/user.pp - ERROR: tab character found on line 11
```

**Comment by mayankkapoor** [comment]
So awesome that this was merged.

**Pull request merged**
