### PR TITLE
Adding SSH key

### PR DESCRIPTION
**Pull request by gdpak**
Add SSH keys

### CODE REVIEW

**Comment by anshprat** [comment]
Hi Deepak,
The last revert was on the entire PR. So you will need to make changes to add the user account in at.yaml as well again.

**Comment by anshprat** [comment]
Also, after adding the at.yaml, please add it to the same commit (git commit --amend) to keep a single commit msg.

**Comment by anshprat** [comment]
looks good. +1 for merging. I would let a second pair of eyes confirm and merge.

**Comment by mayankkapoor** [comment]
Looks fine to me. Merging.

**Pull request merged**
