### PR TITLE
Adding username and ssh key

### PR DESCRIPTION
**Pull request by rahul1aggarwal**

### CODE REVIEW

**Comment by rahul1aggarwal** [comment]
please test this

**Comment by bafna** [comment]
please test this.

**Comment by mayankkapoor** [comment]
@rahul1aggarwal I added you to the Jiocloud team. Now jiojenkins will not ask an admin to verify the patch. One needs to be first added to the Jiocloud team in order to trigger a build using "please test this".

@anshprat I've reviewed the modifications, looks fine to me. As prod isn't working, I recommend going ahead and merging the changes. Would you please review and merge?

**Comment by rahul1aggarwal** [comment]
@mayankkapoor Thanks

**Comment by anshprat** [comment]
Was holding on to this hoping to fix the gates, but looks like it will take some more time. Merging it in the meanwhile. Have verified that the changes are only related to the respective key/user addition and does not impact any other code.

**Comment by rahul1aggarwal** [comment]
@anshprat Thanks

**Pull request merged**
